### ISSUE TITLE
Add simple-table styles from cfgov-refresh

### ISSUE THREAD

**Issue by KimberlyMunoz** [cfpb/cf-tables#2]
Flapjack is using a simple-table style for basic responsive tables.

It should probably get ported to cf-tables.

https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/css/cf-enhancements.less#L306

**Comment by jimmynotjim** [comment]
Just a note. I created the `simple-table` class for these styles rather than making this the default for smaller screens because there are some tables in cfgov-refresh that have different small screen styling and the `simple-table` styles would have to be overwritten and canceled out. I've been trying to doing avoid that in order to keep the size of the stylesheet as small as possible.

**Comment by mistergone** [comment]
This issue is starting to develop a nice patina - is this issue still relevant given v0.1.0 of cf-tables? :grin:

**Comment by KimberlyMunoz** [comment]
I think it's good to close!
